### ISSUE TITLE
wrong status for original messages

### ISSUE THREAD

**Issue by egijasp** [translate-agent/translate#157]
**Expected Result:** if original: true then the status should be translated

**Actual Result:** status: untranslated

`{
    "language": "en",
    "original": true,
    "messages": [
        {
            "id": "comment.label",
            "message": "{Comment}",
            "description": "",
            "status": "UNTRANSLATED",
            "positions": []
        },
        {
            "id": "comment.placeholder",
            "message": "{Enter Comment}",
            "description": "",
            "status": "UNTRANSLATED",
            "positions": []
        }
    ]
}`

**Comment by VladislavsPerkanuks** [comment]
I would say, new status ? e.g. `Original` or `NotToBeTranslated`

**Comment by janishorsts** [comment]
Simply `Translated`. It simplifies a lot of things. Also keeps the size of the proto message down when we choose `Translated` as the default state. Eventually, the majority of the messages are in this state.
