### ISSUE TITLE
Superset pot files  fails convert to our Messages format

### ISSUE THREAD

**Issue by egijasp** [translate-agent/translate#158]
attempts to upload a file (uploadTranslationFile) from Superset messages fail with the error:

`convert from POT schema: divide po file to tokens: failed to parse line: incorrect format of po tags`

**Comment by VladislavsPerkanuks** [comment]
<img width="640" alt="image" src="https://github.com/translate-agent/translate/assets/69954124/7a745a42-bc00-4912-bb57-21ea735e796a">

**Comment by VladislavsPerkanuks** [comment]
already fixed, the new image was not pushed.

Pushed new image, **recreate containers, and everything should work**.

**P.S.** 
Translating won't work as for POT parses messages to be translated to message.ID, which will result in error, when creating/updating messages https://github.com/translate-agent/translate/issues/143. It seems it is not fixed 🤔 

**P.S.S** 
Update grpc-web client, as there were minor changes in proto definition
