### ISSUE TITLE
Enable remaining go linters

### ISSUE THREAD

**Issue by VladislavsPerkanuks** [translate-agent/translate#185]
What linters would we like to use? We won't use deprecated linters.

# Enable:
   - cyclop (n=30?)
   - dogsled
   - dupl
   - dupword
   - forcetypeassert
   - godox
   - gocheckcompilerdirectives
   - goerr113
   - gomoddirectives
   - interface bloat
   - ireturn
   - mirror
   - musttag
   - nilnil
   - nosprintfhostport
   - predeclared
   - reassign
   - rowserrcheck
   - sqlclosecheck
   - stylecheck
   - tagalign
   - tenv
   - usestdlibvars
   -
# Not now 
   - goheader (enable in the future)
   - gosmopolitan
   - maintidx (maybe)
   - nlreturn (maybe, duplicates?)
   - varnamelen

# Disable:
   - asasalint
   - gci (no real benefits)
   - gochecknoglobals
   - gochecknoinits
   - goconst (too many false positives)
   - gofmt (already covered by by gofumpt)
   - deadcode (deprecated)
   - depguard (not applicable)
   - exhaustivestruct (deprecated)
   - exhaustruct (ignore, zero values rule)
   - forbidigo
   - funlen
   - ginkgolinter (not applicable)
   - goimports
   - golint (deprecated)
   - gomodguard
   - grouper
   - ifshort (deprecated)
   - inamedparam
   - interfacer (deprecated)
   - loggercheck
   - maligned (deprecated)
   - nonamedreturns
   - nosnakecase (deprecated)
   - promlinter
   - revive
   - scopelint (deprecated)
   - structcheck (deprecated)
   - testpackage
   - varcheck (deprecated)
   - zerologlint (no applicable)

**Comment by VladislavsPerkanuks** [comment]
All the ones that are in default.  +
[tparallel](https://github.com/moricho/tparallel) : that would save a lot of time for me if it was enabled :)
[testifiylint](https://github.com/Antonboom/testifylint): more correct assertions

I would go with a scenario, in which we enable all linters, except deprecated and overlapping ones. Then we look at warnings, and determine if we want to disable this linter or fix the issue :)

**Comment by klavinsjanis** [comment]
varnamelen: seems good to check

**Comment by janishorsts** [comment]
We'll skip `goerr113` for now. We already use `errorlint` that ensures errors are wrapped. `goerr113` adds an additional check to wrap "static" package errors and forbids creating dynamic unwrapped errors.

**Comment by janishorsts** [comment]
We can ignore `godox` and `dupl`, too.
