### ISSUE TITLE
Google Translate: Some special chars are "translated" which may cause breaking

### ISSUE THREAD

**Issue by VladislavsPerkanuks** [translate-agent/translate#233]
example after translating superset pot to lv po
```po
#: superset-frontend/src/features/home/ChartTable.tsx:200
#: superset-frontend/src/features/home/DashboardTable.tsx:203
#: superset-frontend/src/features/home/SavedQueries.tsx:270
#, fuzzy
msgid "View All »"
msgstr "Apskati visus "" 
```

Due to GoogleTranslate API translating quotation mark to lv quotation mark, it breaks msgstr (unclosed quotation mark)

U+00BB | » | 0xc2 0xbb | RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
-- | -- | -- | --

There might be another cases/characters that can potentially break translation file

**Comment by janishorsts** [comment]
Escape `"` for now. Other escaping characters might be programming language-specific.

**Comment by janishorsts** [comment]
I don't see any meaningful way to resolve Google Translate changing characters - no attempt to solve it.
