### ISSUE TITLE
Configuration file, environment and CLI argument implementation

### ISSUE THREAD

**Issue by VladislavsPerkanuks** [translate-agent/translate#25]
Implementation and naming convention for variables in the configuration file, environment variables and CLI arguments.

_Originally posted by @janishorsts in https://github.com/translate-agent/translate/pull/24#discussion_r1111668376_

**Comment by janishorsts** [comment]
# Binding

In `viper`, the binding is done automatically by matching the names of the environment variables. Viper is case-insensitive.

```yaml
# yaml conf
port: 3000
```

```shell
# env variables
TRANSLATE_PORT=5000
```

```go
// go
viper.SetEnvPrefix("translate") // it'll read all environment variables starting with TRANSLATE
viper.AutomaticEnv()

viper.ReadInConfig() // reads from the configuration file

fmt.Println(viper.GetInt("port")) // prints 5000

// we can bind the env variable manually if required
viper.BindEnv("translate.service.port", "TRANSLATE_PORT")

// bind viper to pflags (cobra)
viper.BindPFlag("service.port", cmd.Lookup("port")))
```

_Can we bind the env variable `TRANSLATE_SERVICE_PORT` to the nested  variable `service.port` automatically?_ 

_How does the binding work with `viper.BindPFlags()`? Exact names? Can we specify the binding function?_ 

# Precedence

`Viper` and `pflags` already implement the order of precedence of reading values (higher priority first):
- CLI arguments (`pflags`)
- environment variables (`viper`)
- configuration file (`viper`)

**Comment by VladislavsPerkanuks** [comment]
>Can we bind the env variable `TRANSLATE_SERVICE_PORT` to the nested variable `service.port` automatically?

Yes, using: 
```go
viper.BindPFlags(rootCmd.Flags())
... // Load config and/or .env
viper.SetEnvPrefix("translate")
viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
viper.AutomaticEnv()
```
If we have environment variable `TRANSLATE_SERVICE_PORT=8080`, then it will be available by `viper.GetInt("service.port")`

Precedence does not change **CLI Arguments > environment variables + environment variables from .env > config file**


>How does the binding work with `viper.BindPFlags()`? Exact names? Can we specify the binding function?

In nutshell `viper.BindPFlags()` binds **flag name** to flag e.g.
```go
rootCmd.PersistentFlags().Uint("port", 0, "port to run")
```
in this scenario calling `viper.BindPFlags()` is equivalent to binding manually 
```go
viper.BindPFlags(rootCmd.Flags()) 
// same as this
viper.BindPFlag("port", rootCmd.Flags().Lookup("port"))
```
The solutions that I see are:
1. Bind all manually e.g.
```go
viper.BindPFlag("port", rootCmd.Flags().Lookup("port"))
... // other binds
```
2. Bind all then bind manually
```go
viper.BindPFlags(rootCmd.Flags())  // bind all
viper.BindPFlag("service.port", rootCmd.Flags().Lookup("port")) // bind service.port to port
... // other manual binds

``` 
In the case of 2. there is side effect e.g.
 ```go
viper.GetInt("service.port") == viper.GetInt("port") 
```
