### ISSUE TITLE
Docker alternatives to create images

### ISSUE THREAD

**Issue by VladislavsPerkanuks** [translate-agent/translate#3]
What are alternatives to creating images for containers? Are there any benefits to using others instead of **docker**?

**Comment by VladislavsPerkanuks** [comment]
Did a research and found 2 alternatives for a docker for creating images.

### Short answer:
Docker's image-building process was improved starting from version 18.09 in 2019, through the use of [Moby/Buildkit](https://github.com/moby/buildkit), which replaced the legacy builder. This provides several benefits, including parallelization, caching, cache import/export, among others. Comparison with other alternatives did not reveal any clear advantage of one over the other

### Longer answer
There is two alternatives, [buildah](https://github.com/containers/buildah) and Google's [kaniko](https://github.com/GoogleContainerTools/kaniko)

#### buildah

Pretty much the same thing as a docker build, but it is open-source and developed by Red Hat. It is available only on Linux but can be used in macOS within [podman](https://github.com/containers/podman), an open-source alternative for docker also developed by Red Hat.

One of the most advertised advantages is you don't need any other tools and daemons to create an image, which is not the case on macOS as you must install podman...
Other listed advantages are:
- Smaller image size than ones that are built with docker (it is often listed as an advantage, but there is no info about how much smaller, or if is it even true)
- Excludes building tools like GCC, from the images, leading to a more secure image.
- Allows creation of single-layer images.

#### kaniko

This one is more specific as its primary purpose is to build images inside another container or Kubernetes. So it is not really an option for us.
Summary from GitHub:
> kaniko doesn't depend on a Docker daemon and executes each command within a Dockerfile completely in userspace. This enables building container images in environments that can't easily or securely run a Docker daemon, such as a standard Kubernetes cluster.


Other alternatives, such as [img](https://github.com/genuinetools/img) or [orca-build](https://github.com/cyphar/orca-build), have been abandoned. My assumption: it is because Docker build and Buildah seem to be doing their job effectively.  Otherwise, if rootless image creation is necessary, Kaniko is a viable option.

**Comment by janishorsts** [comment]
Another alternative is [ko](https://ko.build/) to build Go containers which is [Cloud Native Computing Foundation](https://www.cncf.io/) project. I have tried it in the past with [Knative](https://knative.dev/) but never actually used it in any project.

**Comment by janishorsts** [comment]
Actually, ko uses **docker build** under the hood
